version: "3.8"
services:
  db:
    image: postgres:16
    container_name: ${SERVICE_DB_NAME}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  nextjs:
    container_name: ${SERVICE_NAME}
    build:
      context: ../app
      dockerfile: ./Dockerfile
    command: ["npm", "run", "${NPM_TARGET}"]
    restart: ${RESTART}
    environment:
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=db
      - PGPORT=5432
    ports:
      - "${NEXTJS_PORT}:3000"
    depends_on:
      - db

volumes:
  db_data: